stages:
  - build
  - test
  - release
  - deploy

# Default image for most jobs
image: node:22

build-job:
  stage: build
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-9 --activate
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm i
    - pnpm run build
packages-job:
  stage: release
  image: node:22
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-9 --activate
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm i
    - pnpm run build:pkg
  artifacts:
    paths:
      - bin
  rules:
    - if: '$CI_COMMIT_TAG'   # Run only when a tag is pushed